apps_selection: all-known
dataset_name: CESNET-TLS-Year22
dataset_size: S
datazoo_version: 0.0.7
flowstats_clip: 1
flowstats_scaler: no-scaler
fold_id: 0
ipt_scaler: no-scaler
psizes_scaler: no-scaler
test_period: M-2022-10
train_dataloader_order: sequential
train_period: M-2022-9
use_push_flags: false
use_tcp_features: true
